# Generated by roxyglobals: do not edit by hand

utils::globalVariables(c(
  "age_group", # <get_hosp_for_eval>
  "location", # <get_hosp_for_eval>
  "value", # <get_hosp_for_eval>
  "Datum", # <get_hosp_for_eval>
  "Bundesland", # <get_hosp_for_eval>
  "Altersgruppe", # <get_hosp_for_eval>
  "fixierte_7T_Hospitalisierung_Faelle", # <get_hosp_for_eval>
  "aktualisierte_7T_Hospitalisierung_Faelle", # <get_hosp_for_eval>
  "Bevoelkerung", # <get_hosp_for_eval>
  "state", # <get_hosp_for_eval>
  "updated_hosp_7d_count", # <get_hosp_for_eval>
  "daily_hosp_admits", # <get_hosp_for_eval>
  "state_pop", # <get_hosp_for_eval>
  "init_hosp_7d_count", # <get_hosp_for_eval>
  "location", # <get_initial_values>
  "age_group", # <get_initial_values>
  "value", # <get_initial_values>
  "location", # <reformat_ww_data>
  "state", # <reformat_ww_data>
  "conc", # <reformat_ww_data>
  "pop_cov", # <reformat_ww_data>
  "change_in_lab_indicator", # <reformat_ww_data>
  "normalized", # <reformat_ww_data>
  "pathogen", # <reformat_ww_data>
  "below_LOD", # <reformat_ww_data>
  "site", # <reformat_ww_data>
  "lab", # <reformat_ww_data>
  "log_genome_copies_per_ml", # <reformat_ww_data>
  "log_lod", # <reformat_ww_data>
  "site_pop", # <reformat_ww_data>
  NULL
))
